#!/usr/bin/env bash
# Inatalling Nginx on web-01
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
NGINX_SETUP=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files \$uri \$uri/ =404;
        }

        if (\$request_filename ~ redirect_me){
                rewrite ^ https://sketchfab.com/bluepeno/models permanent;
        }
}"
bash -c "echo -e '$NGINX_SETUP' > /etc/nginx/sites-enabled/default"
if [ "$(pgrep -c nginx)" -le 0 ];
then
        service nginx start
else
        service nginx restart
fi
