#!/usr/bin/env bash
# Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid
pidfl="/var/run/myscript.pid"
cleanup_and_exit() {
	echo "Cleaning up and exiting..."
	rm -f "$pidfl"
	exit 0
}
trap 'cleanup_and_exit' SIGQUIT SIGTERM
handle_sigint() {
	echo "Y U no love me?!"
}
trap 'handle_sigint' SIGINT
handle_sigterm() {
	echo "I hate the kill command"
}
trap 'handle_sigterm' SIGTERM
echo $$ > "$pidfl"
while true; do
	echo "To infinity and beyond"
	sleep 2
done
