#!/usr/bin/env bash
# Bash script that displays Best School 10 times with while loop
# but for the 9th iteration, displays Best School and then Hi on a new line
sum=0
while [ $sum -lt 10 ]
do
	if [ $sum -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( sum++ ))
done
