#!/usr/bin/env bash
# Bash script that loops from 1 to 10 with while loop
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Best School for the other iterations
sum=1
while [ $sum -le 10 ]; do
	if [ $sum -eq 4 ]; then
		echo "bad luck"
	elif [ $sum -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
		((sum++))
done
